//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace OrangeSummer.Web2.UserApplication.kr.co.youiwe.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSMSSoap", Namespace="http://webservice.youiwe.co.kr/")]
    public partial class ServiceSMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSwncOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSCallBackOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSCallBackReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveCancleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRemainCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWeeklyLimitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceSMS() {
            this.Url = global::OrangeSummer.Web2.UserApplication.Properties.Settings.Default.OrangeSummer_Web2_UserApplication_kr_co_youiwe_webservice_ServiceSMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event SendSMSwncCompletedEventHandler SendSMSwncCompleted;
        
        /// <remarks/>
        public event SendSMSReserveCompletedEventHandler SendSMSReserveCompleted;
        
        /// <remarks/>
        public event SendSMSCallBackCompletedEventHandler SendSMSCallBackCompleted;
        
        /// <remarks/>
        public event SendSMSCallBackReserveCompletedEventHandler SendSMSCallBackReserveCompleted;
        
        /// <remarks/>
        public event ReserveCancleCompletedEventHandler ReserveCancleCompleted;
        
        /// <remarks/>
        public event GetRemainCountCompletedEventHandler GetRemainCountCompleted;
        
        /// <remarks/>
        public event GetWeeklyLimitCompletedEventHandler GetWeeklyLimitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/SendSMS", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        smsContent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent) {
            this.SendSMSAsync(smsID, hashValue, senderPhone, receivePhone, smsContent, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        smsContent}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/SendSMSwnc", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMSwnc(string smsID, string hashValue, string gubun, string senderPhone, string receivePhone, string smsContent) {
            object[] results = this.Invoke("SendSMSwnc", new object[] {
                        smsID,
                        hashValue,
                        gubun,
                        senderPhone,
                        receivePhone,
                        smsContent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSwncAsync(string smsID, string hashValue, string gubun, string senderPhone, string receivePhone, string smsContent) {
            this.SendSMSwncAsync(smsID, hashValue, gubun, senderPhone, receivePhone, smsContent, null);
        }
        
        /// <remarks/>
        public void SendSMSwncAsync(string smsID, string hashValue, string gubun, string senderPhone, string receivePhone, string smsContent, object userState) {
            if ((this.SendSMSwncOperationCompleted == null)) {
                this.SendSMSwncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSwncOperationCompleted);
            }
            this.InvokeAsync("SendSMSwnc", new object[] {
                        smsID,
                        hashValue,
                        gubun,
                        senderPhone,
                        receivePhone,
                        smsContent}, this.SendSMSwncOperationCompleted, userState);
        }
        
        private void OnSendSMSwncOperationCompleted(object arg) {
            if ((this.SendSMSwncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSwncCompleted(this, new SendSMSwncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/SendSMSReserve", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMSReserve(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            object[] results = this.Invoke("SendSMSReserve", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        smsContent,
                        reserveDate,
                        reserveTime,
                        userDefine});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSReserveAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            this.SendSMSReserveAsync(smsID, hashValue, senderPhone, receivePhone, smsContent, reserveDate, reserveTime, userDefine, null);
        }
        
        /// <remarks/>
        public void SendSMSReserveAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, string reserveDate, string reserveTime, string userDefine, object userState) {
            if ((this.SendSMSReserveOperationCompleted == null)) {
                this.SendSMSReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSReserveOperationCompleted);
            }
            this.InvokeAsync("SendSMSReserve", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        smsContent,
                        reserveDate,
                        reserveTime,
                        userDefine}, this.SendSMSReserveOperationCompleted, userState);
        }
        
        private void OnSendSMSReserveOperationCompleted(object arg) {
            if ((this.SendSMSReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSReserveCompleted(this, new SendSMSReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/SendSMSCallBack", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMSCallBack(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent) {
            object[] results = this.Invoke("SendSMSCallBack", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        callbackUrl,
                        smsContent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSCallBackAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent) {
            this.SendSMSCallBackAsync(smsID, hashValue, senderPhone, receivePhone, callbackUrl, smsContent, null);
        }
        
        /// <remarks/>
        public void SendSMSCallBackAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, object userState) {
            if ((this.SendSMSCallBackOperationCompleted == null)) {
                this.SendSMSCallBackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSCallBackOperationCompleted);
            }
            this.InvokeAsync("SendSMSCallBack", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        callbackUrl,
                        smsContent}, this.SendSMSCallBackOperationCompleted, userState);
        }
        
        private void OnSendSMSCallBackOperationCompleted(object arg) {
            if ((this.SendSMSCallBackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCallBackCompleted(this, new SendSMSCallBackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/SendSMSCallBackReserve", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMSCallBackReserve(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            object[] results = this.Invoke("SendSMSCallBackReserve", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        callbackUrl,
                        smsContent,
                        reserveDate,
                        reserveTime,
                        userDefine});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSCallBackReserveAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            this.SendSMSCallBackReserveAsync(smsID, hashValue, senderPhone, receivePhone, callbackUrl, smsContent, reserveDate, reserveTime, userDefine, null);
        }
        
        /// <remarks/>
        public void SendSMSCallBackReserveAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, string reserveDate, string reserveTime, string userDefine, object userState) {
            if ((this.SendSMSCallBackReserveOperationCompleted == null)) {
                this.SendSMSCallBackReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSCallBackReserveOperationCompleted);
            }
            this.InvokeAsync("SendSMSCallBackReserve", new object[] {
                        smsID,
                        hashValue,
                        senderPhone,
                        receivePhone,
                        callbackUrl,
                        smsContent,
                        reserveDate,
                        reserveTime,
                        userDefine}, this.SendSMSCallBackReserveOperationCompleted, userState);
        }
        
        private void OnSendSMSCallBackReserveOperationCompleted(object arg) {
            if ((this.SendSMSCallBackReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCallBackReserveCompleted(this, new SendSMSCallBackReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/ReserveCancle", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReserveCancle(string smsID, string hashValue, string searchValue, string mode) {
            object[] results = this.Invoke("ReserveCancle", new object[] {
                        smsID,
                        hashValue,
                        searchValue,
                        mode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveCancleAsync(string smsID, string hashValue, string searchValue, string mode) {
            this.ReserveCancleAsync(smsID, hashValue, searchValue, mode, null);
        }
        
        /// <remarks/>
        public void ReserveCancleAsync(string smsID, string hashValue, string searchValue, string mode, object userState) {
            if ((this.ReserveCancleOperationCompleted == null)) {
                this.ReserveCancleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveCancleOperationCompleted);
            }
            this.InvokeAsync("ReserveCancle", new object[] {
                        smsID,
                        hashValue,
                        searchValue,
                        mode}, this.ReserveCancleOperationCompleted, userState);
        }
        
        private void OnReserveCancleOperationCompleted(object arg) {
            if ((this.ReserveCancleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveCancleCompleted(this, new ReserveCancleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/GetRemainCount", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetRemainCount(string smsID, string hashValue) {
            object[] results = this.Invoke("GetRemainCount", new object[] {
                        smsID,
                        hashValue});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetRemainCountAsync(string smsID, string hashValue) {
            this.GetRemainCountAsync(smsID, hashValue, null);
        }
        
        /// <remarks/>
        public void GetRemainCountAsync(string smsID, string hashValue, object userState) {
            if ((this.GetRemainCountOperationCompleted == null)) {
                this.GetRemainCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRemainCountOperationCompleted);
            }
            this.InvokeAsync("GetRemainCount", new object[] {
                        smsID,
                        hashValue}, this.GetRemainCountOperationCompleted, userState);
        }
        
        private void OnGetRemainCountOperationCompleted(object arg) {
            if ((this.GetRemainCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRemainCountCompleted(this, new GetRemainCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.youiwe.co.kr/GetWeeklyLimit", RequestNamespace="http://webservice.youiwe.co.kr/", ResponseNamespace="http://webservice.youiwe.co.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetWeeklyLimit(string smsID, string hashValue) {
            object[] results = this.Invoke("GetWeeklyLimit", new object[] {
                        smsID,
                        hashValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWeeklyLimitAsync(string smsID, string hashValue) {
            this.GetWeeklyLimitAsync(smsID, hashValue, null);
        }
        
        /// <remarks/>
        public void GetWeeklyLimitAsync(string smsID, string hashValue, object userState) {
            if ((this.GetWeeklyLimitOperationCompleted == null)) {
                this.GetWeeklyLimitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWeeklyLimitOperationCompleted);
            }
            this.InvokeAsync("GetWeeklyLimit", new object[] {
                        smsID,
                        hashValue}, this.GetWeeklyLimitOperationCompleted, userState);
        }
        
        private void OnGetWeeklyLimitOperationCompleted(object arg) {
            if ((this.GetWeeklyLimitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWeeklyLimitCompleted(this, new GetWeeklyLimitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendSMSwncCompletedEventHandler(object sender, SendSMSwncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSwncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSwncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendSMSReserveCompletedEventHandler(object sender, SendSMSReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendSMSCallBackCompletedEventHandler(object sender, SendSMSCallBackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCallBackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCallBackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendSMSCallBackReserveCompletedEventHandler(object sender, SendSMSCallBackReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCallBackReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCallBackReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReserveCancleCompletedEventHandler(object sender, ReserveCancleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveCancleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveCancleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetRemainCountCompletedEventHandler(object sender, GetRemainCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRemainCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRemainCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetWeeklyLimitCompletedEventHandler(object sender, GetWeeklyLimitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWeeklyLimitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWeeklyLimitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591